### ISSUE TITLE
Sequencer/CometBFT tendermint::validator::Update consensus failures 

### ISSUE THREAD

**Issue by Lilyjjo** [astriaorg/astria#967]
CometBFT's logic around adding/removing validators is jagged. I can cause consensus failures with a single validator by sending validator updates to remove either the actual validator or non-existing validators. We need to investigate if sending commands that should be no-ops in a multi validator setup also cause consensus failures to make sure the fix covers those plausible cases as well. 

In general, we shouldn't be able to cause consensus failures by sending incorrect sudo commands. 

Update: can cause consensus failure on multi node network by trying to remove non existing validators as well (!!)

**Comment by Lilyjjo** [comment]
Error from cometBFT on multi node setup when trying to remove non-existing validator:
```
I[2024-04-23|10:32:20.279] updates to validators                        module=state updates=214B269E0F9119BFAC78884EB05E49801B235140:0
E[2024-04-23|10:32:20.280] CONSENSUS FAILURE!!!                         module=consensus err="failed to apply block; error commit failed for application: changing validator set: failed to find validator 214B269E0F9119BFAC78884EB05E49801B235140 to remove" stack="goroutine 2987 [running]:\nruntime/debug.Stack()\n\t/usr/local/go/src/runtime/debug/stack.go:24 +0x64\ngithub.com/cometbft/cometbft/consensus.(*State).receiveRoutine.func2()\n\t/Users/lily/go/pkg/mod/github.com/cometbft/cometbft@v0.38.6/consensus/state.go:801 +0x44\npanic({0x105905980?, 0x1400028c200?})\n\t/usr/local/go/src/runtime/panic.go:770 +0x124\ngithub.com/cometbft/cometbft/consensus.(*State).finalizeCommit(0x14000146008, 0x65)\n\t/Users/lily/go/pkg/mod/github.com/cometbft/cometbft@v0.38.6/consensus/state.go:1780 +0xacc\ngithub.com/cometbft/cometbft/consensus.(*State).tryFinalizeCommit(0x14000146008, 0x65)\n\t/Users/lily/go/pkg/mod/github.com/cometbft/cometbft@v0.38.6/consensus/state.go:1682 +0x26c\ngithub.com/cometbft/cometbft/consensus.(*State).enterCommit.func1()\n\t/Users/lily/go/pkg/mod/github.com/cometbft/cometbft@v0.38.6/consensus/state.go:1617 +0x8c\ngithub.com/cometbft/cometbft/consensus.(*State).enterCommit(0x14000146008, 0x65, 0x0)\n\t/Users/lily/go/pkg/mod/github.com/cometbft/cometbft@v0.38.6/consensus/state.go:1655 +0xabc\ngithub.com/cometbft/cometbft/consensus.(*State).addVote(0x14000146008, 0x1400231c820, {0x1400044a120, 0x28})\n\t/Users/lily/go/pkg/mod/github.com/cometbft/cometbft@v0.38.6/consensus/state.go:2334 +0x1848\ngithub.com/cometbft/cometbft/consensus.(*State).tryAddVote(0x14000146008, 0x1400231c820, {0x1400044a120?, 0x1054b6264?})\n\t/Users/lily/go/pkg/mod/github.com/cometbft/cometbft@v0.38.6/consensus/state.go:2066 +0x28\ngithub.com/cometbft/cometbft/consensus.(*State).handleMsg(0x14000146008, {{0x105ac4c08, 0x1400032e750}, {0x1400044a120, 0x28}})\n\t/Users/lily/go/pkg/mod/github.com/cometbft/cometbft@v0.38.6/consensus/state.go:929 +0x300\ngithub.com/cometbft/cometbft/consensus.(*State).receiveRoutine(0x14000146008, 0x0)\n\t/Users/lily/go/pkg/mod/github.com/cometbft/cometbft@v0.38.6/consensus/state.go:836 +0x2c4\ncreated by github.com/cometbft/cometbft/consensus.(*State).OnStart in goroutine 2824\n\t/Users/lily/go/pkg/mod/github.com/cometbft/cometbft@v0.38.6/consensus/state.go:398 +0xf0\n"
I[2024-04-23|10:32:20.281] service stop                                 module=consensus wal=sequencer_testnet/node0/data/cs.wal/wal msg="Stopping baseWAL service" impl=baseWAL
I[2024-04-23|10:32:20.286] service stop                                 module=consensus wal=sequencer_testnet/node0/data/cs.wal/wal msg="Stopping Group service" impl=Group
I[2024-04-23|10:32:22.839] Timed out                                    module=consensus dur=3s height=101 round=0 step=RoundStepPropose
```

Note the '`changing validator set: failed to find validator`' part.
